config/routes.rb
Rails.application.routes.draw do

  root "pages#home"

  resources :categories, only: [:index, :show]

  resources :walks do
    resources :waypoints
    resources :comments, only: [:show, :create, :destroy]
  end

  post "oauth/callback" => "oauths#callback"
  get "oauth/callback" => "oauths#callback" 
  get "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider
  delete "oauth/:provider" => "oauths#destroy", :as => :delete_oauth

  resources :user_sessions
  resources :users
  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout

  resources :users, only: [:show] do
    resources :walks, only: [:index, :show]
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!
  mount_uploader :icon, IconUploader

  authenticates_with_sorcery! do |config|
    config.authentications_class = Authentication
  end

  has_many :authentications, :dependent => :destroy
  accepts_nested_attributes_for :authentications
  has_many :walks
  has_many :categories, through: :walks


  validates :password, length: { minimum: 6 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }

  validates :email, uniqueness: true

  def has_linked_twitter?
    authentications.where(provider: 'twitter').present?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # before_action :edit_rights?, only: [:update, :edit]
  # before_filter :require_permission, only: :edit

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
    @user_walks = @user.walks
  end

  def create
    @user = User.new(user_params)
    if @user.save
      # UserMailer.welcome(@user).deliver_later
      auto_login(@user)
      redirect_to root_path
    else
      flash[:alert] = "User not created."
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
    unless current_user == @user
      flash[:alert] = "You are not authorized. Currently logged in is #{current_user.username}."
      redirect_to root_url
    end
  end

  def update
    @user = User.find(params[:id])

    if @user.update_attributes(user_params)
      flash[:alert] = "Information updated!"
      redirect_to root_path
    else
      render :edit
    end

  end

  def destroy
    @user = User.find(params[:id])

    @user.destroy
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :username, :email, :icon, :details, :location, :password, :password_confirmation, :authentications_attributes)
  end

  # def edit_rights?
  #   @user = User.find(params[:id])
  #   redirect_to(root_path) unless current_user == @user
  # end

  # def require_permission
  #   if current_user != Walk.find(params[:id]).user
  #     redirect_to root_path
  #   else
  #     redirect_to edit_user_path
  #   end
  # end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <fieldset>
    <ul>
      <li>* Required Field</li>
      <li class ='form_set'><%= f.label :first_name, :class=> 'form_label' %><span class="required">*</span></li>
      <li><%= f.text_field :first_name, :class=>'form_field' %></li>

      <li class ='form_set'><%= f.label :last_name,:class=> 'form_label' %><span class="required">*</span></li>
      <li><%= f.text_field :last_name, :class=>'form_field' %></li>

      <li class ='form_set'><%= f.label :username,:class=> 'form_label' %><span class="required">*</span></li>
      <li><%= f.text_field :username, :class=>'form_field' %></li>

      <li class ='form_set'><%= f.label :email,:class=> 'form_label' %><span class="required">*</span></li>
      <li><%= f.email_field :email, :class=>'form_field' %></li>

      <li class ='form_set'><%= f.label :icon,:class=> 'form_label' %><span class="required">*</span></li>
      <li><%= f.file_field :icon, :class=>'form_field' %></li>

      <li class ='form_set'><%= f.label :details, "About Me",:class=> 'form_label' %><span class="required">*</span></li>
      <li> <%= f.text_area:details, size:'50x10', :class=>'text_area_field', :placeholder =>'Write a description about yourself! (min 250 words)' %></li>
      <li class ='form_set'><%= f.label :location,:class=> 'form_label' %><span class="required">*</span></li>
      <li><%= f.text_field :location, :class=>'form_field' %></li>

      <li class ='form_set'> <%= f.label :password,:class=> 'form_label' %><span class="required">*</span></li>
      <li><%= f.password_field :password, :class=>'form_field' %></li>

      <li class ='form_set'><%= f.label :password_confirmation,:class=> 'form_label' %><span class="required">*</span></li>
      <li> <%= f.password_field :password_confirmation , :class=>'form_field'%></li>

      <br>
      <li><%= f.submit "Save", :class=>"btn_submit" %></li>
    </ul>
  </fieldset>
<% end %>

app/views/users/_nav_menu_not_home.html.erb
<div class="nav-menu-not-home">
  <div class="logo">
    <%= link_to "W", root_path %>
  </div>
  <ul>
    <% if current_user %>
      <li><%= link_to "Create a walk", new_walk_path, :class=>'walk_link' %></li>
      <li><%= link_to "Hi, #{current_user.first_name}!" ,edit_user_path(current_user.id) %></li>
      <li><%= link_to "Logout", :logout, method: :post %></li>
    <% else %>
      <li><span class='login-button'>Create a Walk</span></li>
      <li><span class='login-button'>Login</span></li>
      <li><span id='register-button'>Register</span></li>
      <!-- <li><%#= link_to "Create a walk", new_walk_path %></li> -->
      <!-- <%#= link_to "Register", new_user_path %>
      <%#= link_to "Login", :login, :class=> 'login_link'%> -->
    <% end %>
  </ul>
</div><!-- end of nav-menu-->

app/views/users/edit.html.erb
<div class="page-wrapper">

    <div class="social-media social-login">
        <a href="https://www.facebook.com/walkthiswayvtcm/"><i class="fa fa-facebook" aria-hidden="true"></i></a>
        <a href="https://twitter.com/walkthiswaynow"><i class="fa fa-twitter" aria-hidden="true"></i></a>
        <a href="https://www.instagram.com/walkthiswayvtcm/"><i class="fa fa-instagram" aria-hidden="true"></i></a>
    </div>

    <div class="signup_container">
        <h1 class="login_desc"> Edit your profile... <br></h1>

        <div class="form loginform">
            <% if current_user = @user %>
            <%= render partial: 'form' %>
            <% else %>
            <%= redirect_to walks_path %>
            <% end %>
        </div>

    </div>
</div>

app/views/users/new.html.erb
<div class="page-wrapper">

    <div class="social-media social-login">
        <a href="https://www.facebook.com/walkthiswayvtcm/"><i class="fa fa-facebook" aria-hidden="true"></i></a>
        <a href="https://twitter.com/walkthiswaynow"><i class="fa fa-twitter" aria-hidden="true"></i></a>
        <a href="https://www.instagram.com/walkthiswayvtcm/"><i class="fa fa-instagram" aria-hidden="true"></i></a>
    </div>

    <div class="signup_container">
        <h1 class="login_desc"> Walking is good for you... <br>Sign Up...Get Walking!</h1>

        <div class="form loginform">
            <%= render partial: 'form' %>
        </div>

    </div>
</div>

app/views/users/show.html.erb
<div class = 'profile-container'>


  <div>

    <img src ="<%= @user.icon %>">
  </div>

  <% if current_user == @user %>
  <div class = 'userlinks'>
    <ul class = 'userlink_list'>
      <li><h1 class = 'username-show'><%= @user.first_name %> <%= @user.last_name %> </h1></li>
      <li><%= link_to "Edit Profile", edit_user_url %> </li>
      <li><%= link_to "Walks You've Created", user_walks_url(current_user) %></li>

    </ul>
    </div>
  <% end %>

  <% if current_user.has_linked_twitter? %>
    <%= link_to 'Unlink your Twitter account', delete_oauth_path('twitter'), method: :delete %>
  <% else %>
    <%= link_to 'Link your Twitter account', auth_at_provider_path(:provider => :twitter) %>
  <% end %>

</div>

app/views/users/user_walks.html.erb
<p>hey</p>