config/routes.rb
Rails.application.routes.draw do

  root "pages#home"

  resources :categories, only: [:index, :show]

  resources :walks do
    resources :waypoints
    resources :comments, only: [:show, :create, :destroy]
  end

  post "oauth/callback" => "oauths#callback"
  get "oauth/callback" => "oauths#callback" 
  get "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider
  delete "oauth/:provider" => "oauths#destroy", :as => :delete_oauth

  resources :user_sessions
  resources :users
  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout

  resources :users, only: [:show] do
    resources :walks, only: [:index, :show]
  end
end

app/views/pages/_form.html.erb
<div class = "login_form">
  <%= form_tag user_sessions_path, :method => :post do %>
  <fieldset>
    <ul>
      <!-- <li><%#= link_to "Login with Twitter", auth_at_provider_path(provider: :twitter) %></li> -->
      <li class="form_set">
        <%= label_tag :email, "Email", :class => 'form_label' %>
      </li>
      <li class="form_set">
        <%= text_field_tag :email, "", :id => "form_email" %>
      </li>
      <li class="form_set">
        <%= label_tag :password, "Password", :class => 'form_label' %>
      </li>
      <li class="form_set">
        <%= password_field_tag :password, "", :id => "form_password"%>
      </li>
      <li class="form_set">
        <%= submit_tag "Login", :class => 'btn_submit', :id => "form_submit" %>
      </li>
    </ul>
  </fieldset>
  <% end %>
</div>

app/views/pages/_nav_menu_home.html.erb
<div class="nav-menu-home">
  <div class="logo">
    <%= link_to "W", root_path %>
  </div>

    <ul>
      <% if current_user %>
        <li><%= link_to "Create a walk", new_walk_path, :class=>'walk_link' %></li>
        <li><%= link_to "Hi, #{current_user.first_name}!" ,user_path(current_user.id) %></li>
        <li><%= link_to "Logout", :logout, method: :post %></li>
      <% else %>
        <!-- <li><%#= link_to "Create a walk", new_walk_path %></li> -->
        <!-- <li><%#= link_to "Register", new_user_path %></li>
        <li><%#= link_to "Login", :login, :class=> 'login_link'%></li> -->
        <li><span class='login-button'>Create a Walk</span></li>
        <li><span class='login-button'>Login</span></li>
        <li><span id='register-button'>Register</span></li>
      <% end %>
    </ul>
</div><!-- end of nav-menu-->

app/views/pages/home.html.erb
<!-- being rendered from layouthome.html.erb!!-->