config/routes.rb
Rails.application.routes.draw do

  root "pages#home"

  resources :categories, only: [:index, :show]

  resources :walks do
    resources :waypoints
    resources :comments, only: [:show, :create, :destroy]
  end

  post "oauth/callback" => "oauths#callback"
  get "oauth/callback" => "oauths#callback" 
  get "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider
  delete "oauth/:provider" => "oauths#destroy", :as => :delete_oauth

  resources :user_sessions
  resources :users
  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout

  resources :users, only: [:show] do
    resources :walks, only: [:index, :show]
  end
end

app/models/walk.rb
class Walk < ActiveRecord::Base
  belongs_to :category
  belongs_to :user
  has_many :waypoints
  has_many :comments
  has_many :commenters, through: :comments, source: :user
  has_many :galleries


  geocoded_by :city
  after_validation :geocode

  # reverse_geocoded_by :latitude, :longitude => :city
  # after_validation :reverse_geocode

  mount_uploader :picture, PictureUploader

  validates :city, presence: { message: "City is required" }
  validates :name, presence: { message: "Name of walk is required" }

  validates :description, presence: { message: "Description of walk is required" }
  # validates :picture, presence: { message: "Image of walk is required" }
  validate :need_two_waypoints
  validate :too_many_waypoints

  accepts_nested_attributes_for :galleries
  accepts_nested_attributes_for :waypoints, reject_if: :all_blank

  def need_two_waypoints

    if self.waypoints.length < 2
      errors.add(:walk, "Walks need at least two waypoints.")
    end
  end

  def too_many_waypoints
    if self.waypoints.length > 8
      errors.add(:walk, "Walk is too complicated! Walk has a max number of 8 waypoints (this is a walk, not a hike, or a long and winding spiritual journey with many waypoints)")
    end
  end

  def waypoints_coord_formatted
    if self.waypoints
      self.waypoints.order(:order)
      # ordering by waypoints attribute :order
      waypt_hash = self.waypoints.map { |waypt| [waypt.latitude, waypt.longitude, waypt.address, waypt.description] }
    end
    return waypt_hash.to_json
  end

  def self.filter_by_distance(walk_array, coord_array)
    self.all.each do |walk| #iterate over all Walks in database
      if walk.waypoints.first.distance_from(coord_array) < 30
        walk_array << walk #push this walk into @walks array
      end
    end
  end

  def walk_startpoints(startpt_array)
      startpt_array << [self.waypoints.first.latitude, self.waypoints.first.longitude, self.waypoints.first.address, self.description, self.name, self.id]
  end

end

app/controllers/walks_controller.rb
class WalksController < ApplicationController
  before_action :require_login, only: [:new, :create]
  before_filter :require_permission, only: [:edit, :destroy]


  def index
    if params[:search_by_location].present?
      @walks = []
      @startpoints = []
      @searchedcity = params[:search_by_location]
      @centerpoint = Geocoder.coordinates(params[:search_by_location])
      binding.pry
      Walk.filter_by_distance(@walks, @centerpoint)
    else
      @walks = []
      @startpoints = []
      @walks = Walk.where(city: 'Halifax, NS, Canada')
      @centerpoint = Geocoder.coordinates('Halifax, NS')
      @searchedcity = 'Halifax, NS';
    end

    # playing with geocoder
    if params[:geolocate_lat]
      @walks = []
      @startpoints = []
      @centerpoint = [params[:geolocate_lat], params[:geolocate_lon]]
      @searchedcity = Geocoder.address(@centerpoint)
      @walks = Walk.near([params[:geolocate_lat], params[:geolocate_lon]], 20, :units => :km)
    end

    if params[:search_by_category]
      @category = params[:search_by_category].to_i
      @walks = @walks.select{|walk| walk.category.id ==  @category}
      if @walks != nil
        @walks.each {|walk| walk.walk_startpoints(@startpoints)}
      end
    end

    if params[:user_id]
      @walks = User.find(params[:user_id]).walks
    end

    if @walks != nil
      @walks.each {|walk| walk.walk_startpoints(@startpoints)}
    end

    if request.xhr?
      render @walks
    end
  end

  def new
    @walk = Walk.new
    # @walk.plot_waypoints(params[:waypoint])

    @allwaypoints = []
    if params[:waypoints]

      i=0
      params[:waypoints].each do |waypt|
        waypt = params[:waypoints][i.to_s]
        latlong = Geocoder.coordinates(waypt[:address])
        @allwaypoints.push([latlong[0], latlong[1], "", ""])
        i+=1
      end
    end

    respond_to do |format|
      format.html
      format.json { render json: @allwaypoints}
    end

  end

  def show
    @walk = Walk.find(params[:id])
    @centershow = [@walk.waypoints.first.latitude, @walk.waypoints.first.longitude]
    @allwaypoints = @walk.waypoints_coord_formatted

    if current_user
      @comment = @walk.comments.new
    end
    if @walk.comments.any?
      @comments = Comment.where(walk_id: params[:id])
    end

    respond_to do |format|
      format.html
      format.json { render json: @allwaypoints}
    end
  end


  def create
    @walk = Walk.new(walk_params)
    @walk.user_id = current_user.id

    if @walk.save
      redirect_to walk_path(@walk)
    else
      render :new
      flash.now[:alert] = 'failed'
    end
  end

  def update
    @walk = Walk.find(params[:id])
    if @walk.update(walk_params)
      redirect_to walk_url(@walk)
    else
      render :edit
    end
   end

   def edit
    @walk = Walk.find(params[:id])
   end

   def destroy
     @walk = Walk.find(params[:id])
     @walk.destroy

     redirect_to walks_url
   end

   def require_permission
     if current_user != Walk.find(params[:id]).user
       redirect_to walk_url
     end
   end

  private

  def walk_params
    params.require(:walk).permit(:city, :name, :description, :picture, :category_id, :user_id, :longitude, :latitude, waypoints_attributes: [:name, :description, :address, :longitude, :latitude, :order, :index])
  end

end

app/helpers/walks_helper.rb
module WalksHelper
end

app/views/walks/_comment.html.erb
<div id = 'comment-list-and-form'>

  <h3 class = 'comment-title'> Comments </h3>
<ul class="comments">
  <% if @walk.comments.any? %>
    <% @walk.comments.each do |comment| %>
      <% if comment.id != nil %>
        <li class="comment-list">
          <p class = 'comment-text'><%= comment.comment %></p>
          <p class='comment-author-date'>
            <span class="comment_by">by</span> <span class="comment_author"><%= User.find(comment.user_id).username %></span> <time class="comment-time"><%= comment.created_at.strftime('%b %e, %l:%M %p') %></time>
          </p>
          <p>
            <% if comment.user = current_user %>
             <%= link_to 'Delete', [@walk, comment], method: :delete, data: {confirm: "Confirm delete?"}, class:"delete-comment" %>
           <% end %>
          </p>
        </li>
      <% end %>
    <% end %>
  <% end %>
</ul>
  <% if current_user %>
  <p class="leave_comment"> Leave a comment! </p>
    <%= form_for [@walk, @comment], :html => {:id => 'commentform', :data => {:walkid => @walk.id} } do |f| %>
      <%= f.text_area :comment, placeholder: "This walk was just fab.", class:'comment_textbox' %>
      <%= f.submit "post", id: "post-comment" %>
    <% end %>
  <% end %>

</div>

app/views/walks/_commentlist.html.erb
<div id = 'comment-list-and-form'>

  <h3 class = 'comment-title'> Comments </h3>
<ul class="comments">
  <% if @walk.comments.any? %>
    <% render @comments %> 
  <% end %>
</ul>
  <% if current_user %>
  <p class="leave_comment"> Leave a comment! </p>
    <%= form_for [@walk, @comment], :html => {:id => 'commentform', :data => {:walkid => @walk.id} } do |f| %>
      <%= f.text_area :comment, placeholder: "This walk was just fab.", class:'comment_textbox' %>
      <%= f.submit "post", id: "post-comment" %>
    <% end %>
  <% end %>

</div>

app/views/walks/_form.html.erb
    <%= form_for @walk, :html => { class: "form_edit_new" } do |f| %>
      <ul class="js_errors_list">
        <!-- clientside error validations will go here -->
      </ul>

      <% if @walk.errors.any? %>
        <div id="error_explanation">
          <ul>
            <% @walk.errors.each do |key, value|  %>
               <%if key != :walk%>
                  <li><%= value%></li>
               <%end%> <!-- end of if key walk -->
            <% end %><!-- end of walk errors each do -->
          </ul>


          <% if (@waypoint != nil) && (@waypoint.errors.any?) %>
            <ul>
              <% @waypoint.errors.each do |key, value| %>
                  <li><%= key %><%= value %></li>
              <% end %>
            </ul>
          <% end %>
        </div><!-- end of error_explanation-->
      <% end %>

    <fieldset>
      <div class="steps_container">
          <div class="create_step create_form_step_one">
              <h3 class="create_step_one_title">STEP 1: DESCRIBE WALK</h3>

              <div class ='form_set'>
                  <%= f.label :city,:class=> 'form_label form_label_create_walk'  %><span class="required">* </span>
                  <%= f.text_field :city, :id=>'form_city', :class=>'form_field form_field_create_walk autocomplete_city form_create_address'%>
                  <button type="button" id="centerbutton">CENTER MAP</button>
              </div>

            <div class ='form_set'>
                <%= f.label :category, :class=> 'form_label form_label_create_walk' %><span class="required">*  </span>
                <%= f.collection_select(:category_id, Category.all, :id, :theme) %>
            </div>

            <div class ='form_set'>
                <%= f.label :name,:class=> 'form_label form_label_create_walk'  %><span class="required">* </span>
                <%= f.text_field :name, :class=>'form_field form_field_create_walk form_create_name', :id=>'form_name' %>
            </div>

            <div class ='form_set'>
                <%= f.label :description,:class=> 'form_label form_label_create_walk'  %><span class="required">* </span>
                <%= f.text_area :description, :class=>'form_field desc_field_create_walk form_create_desc ', :id=>'form_desc' %>
            </div>

          <div class ='form_set'>
              <%= f.label :picture,:class=> 'form_label form_label_create_walk'  %>
              <%= f.file_field :picture, :class=>'form_field form_field_create_walk form_create_picture' %>
          </div>
        </div><!-- end of create_form_step_one-->

        <div class="create_step create_form_step_two">
            <h3 class="create_step_two_title">STEP 2: WAYPOINTS (STOPS)</h3>

            <p class="waypoint_desc">You may create up to 8 waypoints for your walk. You can order your waypoints by dragging them. </p>

              <div id="sortable">
                <div id="mkpts">
                  <%= f.fields_for :waypoints do |waypoint| %>
                    <%= render 'waypoint_fields', :f => waypoint%>
                  <% end %>
                  <span class="add_waypoint">Add New Waypoint</span><%= link_to_add_association '+', f, :waypoints, :class=> 'plus'%>
                </div><!-- end of mkpts-->
              </div><!-- end of sortable-->

        </div><!-- end of create_form_step_two-->

        <div class="create_step create_form_step_three">
            <h3 class="create_step_two_title">Step 3 - Plot and save your walk!</h3>
            <div>
              <p>You can view what your walk will look like on a map by clicking on the 'Plot this walk' button. When you are satisfied with the walk, click the 'create walk' button below.  </p>
              <button type = 'button' class = 'plot_walk_btn'> plot this walk! </button>

            </div>

        </div><!-- end of create_form_step_three-->

      </div><!-- end of steps container-->

        <div class="back_next_container">
          <button type="button" class="step_btn back_btn">BACK </button>
          <button type="button" class="step_btn next_btn">NEXT </button>
              <%= f.submit "CREATE WALK" , :class=>'walk_submit step_btn' %>
        </div>

    </fieldset>
    <% end %><!-- end for form for -->

app/views/walks/_like.html.erb
<div id = 'likeorunlike'>
  <% if @like != nil %>
    <%= render partial: 'bookmarkedwalks/unlike_button' %>
  <% else %>
    <div id='likebtn'>
      <%= render partial: 'bookmarkedwalks/like_button' %>
    </div>
  <% end %>
</div>


  <% if @total_likes > 1 %>
    <%= @total_likes %> people liked this walk!
  <% elsif @total_likes == 1%>
    <%= @total_likes %> person liked this walk!
  <% else %>
    Be the first to like this walk!
  <% end %>

app/views/walks/_walk.html.erb
<section class="walk">
  <%= link_to walk.name, walk %>
</section>

app/views/walks/_waypoint_fields.html.erb
<div class="nested-fields">
  <fieldset>
      <div class ='form_set'>
        <%= f.label :address,:class=> 'form_label_create_walk waypoint_label'  %>
        <%= f.text_field :address,:class=>"address form_field_create_walk_address"%>
      </div>

      <div class ='form_set'>
        <%= f.label :description, :class=> 'form_label_create_walk waypoint_label' %>
        <%= f.text_area :description,:class=>"description"%>
      </div>

      <li><%= f.hidden_field :order, :class=>"order" %></li>

      <i class="fa fa-hand-grab-o" aria-hidden="true"></i>

      <%= link_to_remove_association "Remove Waypoint", f, :class=>"cancel_waypoint" %>
        <button class ="plot_btn" type="button">Plot on Map</button>

  </fieldset>
</div>

app/views/walks/edit.html.erb
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js" ></script>


  <h1 class="create_walk_title edit_title">
    We all make mistakes ... </br>
    Edit your walk.
  </h1>

<div class="edit_main">
  <div class="form-list">
    <%= render partial: 'form'  %>
  </div>

<div id="map_walk-form" class="map" data-latitude='0' data-longitude="0" ></div>
</div>

app/views/walks/index.html.erb
<div class="index_container">
  <div class="page-wrapper">
    <h1 class="index_title">Walks around <%= @searchedcity %></h1>

  <div class="search-geolocate">
    <div>
      <%= form_tag(walks_path, method: "get", id:'search_by_category') do %>
        <%= label_tag(:search_by_category, "Category:") %>
      <%= select_tag(:search_by_category, options_from_collection_for_select(Category.all, "id", "theme"), :selected => params[:search_by_category], :class=>'category_dropdown') %>
      <%= hidden_field_tag :search_by_location, params[:search_by_location] %>
      <%= submit_tag "Search by Category", :class=>"category_btn" %>
      <% end %>
    </div>

    <!-- <button type="button" id='geolocate_me'>Find walks near me! </button> -->

    <div class = "geolocate-btn">
      <%= form_tag(walks_path, method: "get", :id => 'geolocate_form') do%>
      <%= hidden_field_tag :geolocate_lat, params[:lat], :id=> 'hidden_geolocate_tag_lat'%>
      <%= hidden_field_tag :geolocate_lon, params[:lon], :id=> 'hidden_geolocate_tag_lon'%>
      <%= submit_tag "Find walks near me!", :class => "category_btn", :id => 'geolocate_me' %>
      <% end %>
    </div>

  </div>

  <div id="map_walk-index" data-latitude="<%= @centerpoint[0] %>" data-longitude="<%= @centerpoint[1] %>" data-startpoints = "<%= @startpoints %>" >
  </div>


  <div class='tweets'>
    <div class='index-buttons'>
      <a href="https://twitter.com/intent/tweet?button_hashtag=walkthiswaypath" class="twitter-hashtag-button" data-size="default" data-related="walkthiswaynow">Tweet #walkthiswaypath</a>
    </div>
    <a class="twitter-timeline"
      data-dnt="true"
      data-widget-id="739155615986163713"
      width="98%"
      border-color="#f3007a"
      data-chrome="nofooter noheader"
      data-tweet-limit = "5"
      data-aria-polite="assertive">
    </a>
    <script>window.twttr = (function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0],
        t = window.twttr || {};
      if (d.getElementById(id)) return t;
      js = d.createElement(s);
      js.id = id;
      js.src = "https://platform.twitter.com/widgets.js";
      fjs.parentNode.insertBefore(js, fjs);
      t._e = [];
      t.ready = function(f) {
        t._e.push(f);
      };
      return t;
    }(document, "script", "twitter-wjs"));</script>
  </div><!-- end of twitter -->

<button class="create_walk_btn" type="submit"><%= link_to "Create a walk", new_walk_path %></button>
</div><!-- end of page-wrapper-->



<div class="walks_container">
  <div class="page-wrapper">
    <div class="walks-list">
      <% @walks.each do |walk| %>
        <div class="walkcard" style="background-image: url('<%= walk.picture%>');">
          <%= link_to walk_path(walk) do %>
        <p class="walkcard_name"><%= walk.name%></p>
        <p class="walkcard_desc"><%= walk.description%></p>
      </div>
  <% end %>
  <% end %>
</div>

  </div><!-- end of walks-page-wrapper -->
  </div> <!-- end of walks container-->
</div>

app/views/walks/new.html.erb
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js" ></script>

<div class="create_walk_container">
  <div class="page-wrapper">
    <h1 class="create_walk_title">Have an awesome path you want to share?</br>
      Create a route!</h1>
  </div><!-- end of page wrapper-->

  <div class="form-list">
      <%= render partial: 'form'  %>
  </div><!-- end of form_list -->

      <div id="map_walk-form" class="map" data-latitude='0' data-longitude="0" ></div>


</div><!-- end of create walk container-->

app/views/walks/show.html.erb
<div class="walk_show_hero" style="background: url('<%=@walk.picture%>') no-repeat; background-size:cover; ">
  <div class="walk_show_title">
    <div class="walk_show_name">
      <%= @walk.name %>
    </div>
    <div class="walk_show_city">
      <%= @walk.city %>
    </div>
  </div>
  <div class="walk_show_overlay">
  </div>
</div>



<main class="walk_show_main">

  <div id = 'directions-modal'>
    <div id='hide-directions'> X </div>
    <div id='directions-panel'>Directions </div>
  </div>

  <div class= "walk_show_left">

    <% if current_user == Walk.find(params[:id]).user %>
      <%= link_to '<i class="fa fa-pencil"></i>'.html_safe, edit_walk_path %>
      <%= link_to '<i class="fa fa-trash-o"></i>'.html_safe, @walk, method: :delete, data: { confirm: 'Are you sure you want to delete your walk?' } %>
    <% end %>

    <div class="show_section">
      <h2 class="walk_show_about">About This Walk</h2>
      <p class="walk_show_description"><%=@walk.description%></p>
    </div>

    <div class="show_section">
        <h2 class="walk_show_route">Walk Route</h2>

        <div class="waypoints_form">
          <% i = 1 %>
          <% @walk.waypoints.each do |waypoint| %>
            <span class="waypoint_stop"><%= "Stop #{i}: "%></span> <%= waypoint.address %>
              <!-- <%#= waypoint.description %> -->
            <% i+= 1%> <br>
          <% end %>
        </div>
    </div>

    <div class="show_section">
      <div class = 'walk-show-summary'>Length of Walk </div>
      <div id='directions-panel-summary'></div>
      <div class = 'walk-show-directions'>Click for Directions </div>
    </div>
  </div><!-- end of walk_show_left-->


  <div class="walk_show_right">
    <div id="map_walk-show" class="map" data-latitude="<%= @centershow[0] %>" data-longitude="<%= @centershow[1] %>"></div>
  </div>


</main>

    <div class="page-wrapper">
      <%= render 'comment'%>
    </div>